server {
    listen 443 ssl;
    server_name jack.42.fr jack.go.htmx; 

    ssl_certificate /etc/nginx/ssl/gohtmx.crt;
    ssl_certificate_key /etc/nginx/ssl/gohtmx.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    # Radice per i file statici condivisi tramite il volume static_data
    location /static/ {
        alias /usr/share/nginx/html/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Proxy inverso per l'applicazione Go per tutte le altre richieste
    location / {
        proxy_pass http://go-app:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}